services:
  - type: web
    name: learnix-backend
    root_dir: backend
    runtime: node
    buildCommand: npm ci
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    autoDeploy: true
